package com.campusfind.controller;

import com.campusfind.entity.*;
import com.campusfind.repository.*;
import com.campusfind.service.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.annotation.Transactional;
import java.security.Principal;
import java.time.Instant;
import java.util.*;

@RestController
@RequestMapping("/api/admin")
public class AdminController {
    private final Support support;private final UserRepository users;private final ItemRepository items;private final ClaimRepository claims;private final AuditRepository audit;private final CategoryRepository categories;private final LocationRepository locations;private final AnnouncementRepository announcements;private final ItemService itemService;
    public AdminController(Support support,UserRepository users,ItemRepository items,ClaimRepository claims,AuditRepository audit,CategoryRepository categories,LocationRepository locations,AnnouncementRepository announcements,ItemService itemService){this.support=support;this.users=users;this.items=items;this.claims=claims;this.audit=audit;this.categories=categories;this.locations=locations;this.announcements=announcements;this.itemService=itemService;}
    private UserAccount admin(Principal p){UserAccount a=support.user(p);support.admin(a);return a;}
    private Map<String,Object> userView(UserAccount u){Map<String,Object> v=new LinkedHashMap<>();v.put("id",u.id);v.put("name",u.name);v.put("email",u.email);v.put("collegeId",u.collegeId);v.put("department",u.department);v.put("role",u.role);v.put("verified",u.verified);v.put("emailVerified",u.emailVerified);v.put("identityVerified",u.identityVerified);v.put("active",u.active);v.put("flagged",u.flagged);v.put("reputation",u.reputation);v.put("createdAt",u.createdAt);v.put("unsuccessfulClaims",claims.findByClaimantId(u.id).stream().filter(c->"REJECTED".equals(c.status)).count());return v;}
    @GetMapping public Object dashboard(Principal p){UserAccount a=admin(p);List<Item> all=items.findAll();List<Claim> allClaims=claims.findAll();Map<String,Object> stats=new LinkedHashMap<>();stats.put("users",users.count());stats.put("lost",all.stream().filter(i->i.type.equals("LOST")&&ItemService.open(i)).count());stats.put("found",all.stream().filter(i->i.type.equals("FOUND")&&ItemService.open(i)).count());stats.put("matches",itemService.matches(a).size());stats.put("pendingClaims",allClaims.stream().filter(c->Set.of("FINDER_REVIEW","ADMIN_REVIEW","MORE_INFORMATION_REQUIRED").contains(c.status)).count());stats.put("returned",all.stream().filter(i->i.type.equals("FOUND")&&i.status.equals("RETURNED")).count());stats.put("flagged",users.findAll().stream().filter(u->u.flagged).count());long totalFound=all.stream().filter(i->i.type.equals("FOUND")).count();stats.put("recoveryRate",totalFound==0?0:Math.round(100.0*(long)stats.get("returned")/totalFound));
        return Map.of("stats",stats,"users",users.findAll().stream().map(this::userView).toList(),"items",all.stream().map(itemService::publicView).toList(),"claims",allClaims.stream().map(c->Map.of("id",c.id,"item",itemService.publicView(c.item),"claimantName",c.claimant.name,"status",c.status,"score",c.score,"createdAt",c.createdAt)).toList(),"audit",audit.findAll().stream().sorted(Comparator.comparing((AuditEvent e)->e.createdAt).reversed()).limit(200).toList(),"categories",categories.findAll(),"locations",locations.findAll(),"announcements",announcements.findAll());
    }
    @PostMapping("/users/{id}") @Transactional public Object user(@PathVariable long id,@RequestBody Map<String,String> d,Principal p){UserAccount a=admin(p),u=users.findLockedById(id).orElseThrow();String action=d.getOrDefault("action","");ItemService.check(!a.id.equals(u.id),"Use your profile for your own account; another administrator must review administrative changes");ItemService.check(!"ADMIN".equals(u.role),"Administrator accounts cannot be changed from the public account management screen");switch(action){case "VERIFY"-> {ItemService.check(u.collegeId!=null&&!u.collegeId.isBlank(),"A college ID is required");u.identityVerified=true;u.verified=u.emailVerified;}case "DEACTIVATE"->u.active=false;case "ACTIVATE"->{u.active=true;u.failedAttempts=0;u.lockedUntil=null;}case "FLAG"->u.flagged=true;case "UNFLAG"->u.flagged=false;default->throw new IllegalArgumentException("Choose a valid account action");}users.save(u);support.audit(a,"ADMIN_USER_"+action,"user:"+id);support.notify(u,"Account updated",action.equals("VERIFY")?"Your college ID was reviewed. "+(u.emailVerified?"Your account is verified.":"Please verify your email to finish account verification."):"Campus administration updated your account status.");return userView(u);}
    @PostMapping("/categories") @Transactional public Object category(@RequestBody Map<String,String> d,Principal p){UserAccount a=admin(p);String name=name(d);ItemService.check(!categories.existsByName(name),"This category already exists");Category c=new Category();c.name=name;categories.save(c);support.audit(a,"CATEGORY_CREATED","category:"+c.id);return c;}
    @DeleteMapping("/categories/{id}") @Transactional public Object deleteCategory(@PathVariable long id,Principal p){UserAccount a=admin(p);Category c=categories.findById(id).orElseThrow();ItemService.check(items.findAll().stream().noneMatch(i->i.category.equals(c.name)),"This category is used by existing reports");categories.delete(c);support.audit(a,"CATEGORY_DELETED","category:"+id);return Map.of("ok",true);}
    @PostMapping("/locations") @Transactional public Object location(@RequestBody Map<String,String> d,Principal p){UserAccount a=admin(p);String name=name(d);ItemService.check(!locations.existsByName(name),"This location already exists");CampusLocation l=new CampusLocation();l.name=name;locations.save(l);support.audit(a,"LOCATION_CREATED","location:"+l.id);return l;}
    @DeleteMapping("/locations/{id}") @Transactional public Object deleteLocation(@PathVariable long id,Principal p){UserAccount a=admin(p);CampusLocation l=locations.findById(id).orElseThrow();ItemService.check(items.findAll().stream().noneMatch(i->i.location.equals(l.name)),"This location is used by existing reports");locations.delete(l);support.audit(a,"LOCATION_DELETED","location:"+id);return Map.of("ok",true);}
    private String name(Map<String,String> d){String name=d.getOrDefault("name","").trim();ItemService.check(name.length()>=2&&name.length()<=80,"Name must contain 2–80 characters");return name;}
    @PostMapping("/announcements") @Transactional public Object announce(@RequestBody Map<String,String> d,Principal p){UserAccount a=admin(p);String title=d.getOrDefault("title","").trim(),message=d.getOrDefault("message","").trim();ItemService.check(title.length()>=3&&title.length()<=120&&message.length()>=5&&message.length()<=1500,"Enter a title (3–120 characters) and message (5–1500 characters)");Announcement n=new Announcement();n.title=title;n.message=message;n.createdAt=Instant.now();announcements.save(n);support.audit(a,"ANNOUNCEMENT_CREATED","announcement:"+n.id);return n;}
    @DeleteMapping("/announcements/{id}") @Transactional public Object deleteAnnouncement(@PathVariable long id,Principal p){UserAccount a=admin(p);announcements.deleteById(id);support.audit(a,"ANNOUNCEMENT_DELETED","announcement:"+id);return Map.of("ok",true);}
    @PostMapping("/items/{id}") @Transactional public Object moderate(@PathVariable long id,@RequestBody Map<String,String> d,Principal p){UserAccount a=admin(p);Item i=items.findLockedById(id).orElseThrow();String action=d.getOrDefault("action","");ItemService.check(claims.findByItemId(id).stream().noneMatch(c->!Set.of("REJECTED","CLOSED","RETURN_CONFIRMED").contains(c.status)),"Resolve active claims before moderating this report");switch(action){case "CLOSE"->i.status="CLOSED";case "REMOVE"->i.status="REMOVED";case "RESTORE"->{ItemService.check(!"RETURNED".equals(i.status),"Returned items cannot be reopened");i.status=i.type.equals("LOST")?"LOST":"AVAILABLE_FOR_CLAIM";}default->throw new IllegalArgumentException("Choose close, remove, or restore");}i.updatedAt=Instant.now();items.save(i);support.audit(a,"REPORT_"+action,"item:"+id);support.notify(i.owner,"Report reviewed","Campus administration updated ‘"+i.title+"’ to "+i.status.toLowerCase().replace('_',' ')+".");return itemService.publicView(i);}
}
